image: rabits/qt:5.9-desktop

stages:
  - build
  - test

job1:
  stage: build
  script:
    - qmake *.pro
    - make qmake_all
    - make
  cache:
    - .qmake.stash
    - Makefile
    - bin/
    - build/
    - src/VisualDBEditor/Makefile
    - tests/Makefile
    - tests/TestXmlDB/Makefile
    - tests/TestXmlDB/TestXmlDB
    - tests/TestXmlDB/target_wrapper.sh
    
job2:
  stage: test
  script:
    - make check
