image: rabits/qt:5.9-desktop

stages:
  - build
  - test

job1:
  stage: build
  script:
    - qmake *.pro
    - make qmake_all
    - make
  artifacts:
    untracked: true
    
job2:
  stage: test
  script:
    - make check
  artifacts:
    untracked: true
